### PR TITLE
UOL's DiRAC apps minor update...

### PR DESCRIPTION
**Pull request by asifsamiarain**
`+ python excalibur-tests/post-processing/post_processing.py perflogs ppp_config.yaml -d -v
Found log files:
- perflogs/dial3/compute-node/Sphng_Strong_Scaling_evolution.log
- perflogs/dial3/compute-node/Osu_allreduce.log
- perflogs/dial3/compute-node/Osu_bibw.log
- perflogs/dial3/compute-node/TROVE_14N.log
- perflogs/dial3/compute-node/TROVE_12N.log
- perflogs/dial3/compute-node/Osu_bw.log
- perflogs/dial3/compute-node/Sphng_Weak_Scaling_evolution.log
- perflogs/dial3/compute-node/Osu_latency.log
- perflogs/dial3/compute-node/RamsesMPI_weak.log
- perflogs/dial3/compute-node/Osu_allgather.log
- perflogs/dial3/compute-node/TROVE_16N.log
- perflogs/dial3/compute-node/RamsesMPI_strong.log
- perflogs/dial3/compute-node/PdsyevSingle.log
- perflogs/dial3/compute-node/Osu_alltoall.log
- perflogs/dial3/compute-node/Sphng_Single_Node_evolution.log

Discarding Sphng_Strong_Scaling_evolution.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding TROVE_14N.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding TROVE_12N.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding Sphng_Weak_Scaling_evolution.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding RamsesMPI_weak.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding TROVE_16N.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding RamsesMPI_strong.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

Discarding Sphng_Single_Node_evolution.log: KeyError: Perflog missing one or more required fields ['job_completion_time', '\\w+_value$', '\\w+_unit$', 'display_name']

KeyError: ('Could not find columns', ['Total elapsed time_value'])
Post-processing stopped`

### CODE REVIEW

**Review by giordano — APPROVED** [review]
Out of curiosity, was this a problem with spaces in the key name?

**Comment by asifsamiarain** [comment]
That's what my impression is, "spaces in the key name" seems problematic.

**Comment by mirenradia** [comment]
I think this change has broken things for me (at least for the ramses benchmark). I presume the intention was to change the `perf_key`s but I think the pattern matches should be the old ones.

**Comment by asifsamiarain** [comment]
Thanks for testing @mirenradia seems like a typo, I will test and get this fixed in next merge.

**Pull request merged**
