### PR TITLE
Add data transformations for post-processing plot data

### PR DESCRIPTION
**Pull request by pineapple-cat**
Addresses #183 and #205.

- [x] Fix categorical sorting.
- [x] Add unit tests.
- [x] Update documentation.

### CODE REVIEW

**Comment by pineapple-cat** [comment]
I still can't replicate exactly what's going wrong with Asif's example, but the scaling issue Tuomas found was caused by a `num_cores` mismatch, which I fixed by sorting the dataframe before scaling.

fixed_si_weak_scaling

**Comment by asifsamiarain** [comment]
Thanks @pineapple-cat for the fix and now we may see the plot look like:

image

Still wonder, how to order w.r.t. series rather x-axis?

Here is below an example to give a quick look at the perflogs data:

```
import os
import glob
import pandas as pd
from pivottablejs import pivot_ui
 
path = os.getcwd()
files = glob.glob(os.path.join(path,"perflogs/*/*/*.log"))
df_list = (pd.read_csv(file, delimiter="|") for file in files)
df = pd.concat(df_list, ignore_index=True)
pivot_ui(df)
```

Above code will generate a browser viewable pivottablejs.html file (and above similar Sphng Single Node data w.r.t. 20230707, 20231013, 20231124 job completion times will look like grouped+ordered as shown below):

image

**Review by tkoskela — COMMENTED** [review]
The documentation makes sense to me. A couple of suggestions:
- It might be easier to understand if the examples were in figures instead of tables.
- Instead of *A note on X* I would just have *X* as the subtitle.

While playing with Asif's logfiles, I noticed one more bit of odd behaviour. When I use the full datetime as the x axis, the series don't get sorted by `num_tasks_per_node` (or rather, it looks like they are ordered by the x axis value of the first element in the series).
image
If I drop the time from the datetimes, so that my series get grouped together on the x axis, I get the series sorted by `num_tasks_per_node`
image
Is this a bug or a feature?

Should we include some general formatting options in the config file? Something to think about for future. Things I always end up hacking by hand include
- orientation of the x axis labels
- export to png

**Comment by pineapple-cat** [comment]
Bokeh has its own x-axis sorting method that I need to undermine at every step if we want non-string data to be sorted properly on a categorical plot. I've fixed this for (x, series) groupings in the commit below, but this will need to be revisited if we want to expand to (x, series1, series2) groupings. Here's what the plot should look like now:

#### Ascending
sphng_single_node_ascending
#### Descending
sphng_single_node_descending

Additionally, there's no need to hack anything to produce a PNG of the graph; this feature is available through the 'Save' button in the Bokeh toolbar:

bokeh_toolbar

**Review by ilectra — APPROVED** [review]

**Pull request merged**
